package test

import (
	"context"
	"fmt"
	"github.com/braid2048/sugar/conv"
	"github.com/braid2048/sugar/conv/types"
	"testing"
)

func TestAlipay(t *testing.T) {
	convReq := &types.ConvReq{
		BaseParams: &types.BaseConv{ // ---- 基础参数都是必传
			PID:     "test_pid_01",
			AdID:    "test_adid_01",
			Channel: "honor",
			Brand:   "huawei",
			Ip:      "127.0.0.1",
		},
		AlipayParams: &types.AlipayConv{
			AppID:           "test_app_id",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 支付宝分配给开发者的应用ID 必填
			PrivateKey:      "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiFsqCUKrR3ZI+Ew3rOmODb3sdB6pLnIdNVk3/u32Q5tt7OXNEdt2TTFtmWvUub53NL+lGoRqzWZ8RWwkWtBN6C3cYCjA+jtS38I49MPabDkwUUI58C2cy7msRt5ovaDluAr4aDZ3DrO4VjkGg4LwseWuls9Mp1FbMYTWetFrP2XmuqREKMQ6upEFz+Q0MBHF5gMyBSEUWdpaTFPCmRWqFXuyuR5/7w6QUfa/OyyOUObhxGq1z6f8+KKB0j2DvtuS8NVYhdmtHvJMfMcl19d2eyR4b0NAbObYJwORtmHmYzE3unz8OaViYdYvH2ScakSM96Ijh/iekHKVP1Yz+S9kXAgMBAAECggEATxjKF8+fnCwAynPn7esfVqtXK7Jq4tzulcnQ5EOtIcHWRwqg+j77H386dvdaACANpGyF7KZ/bhgE7KY9CCw1+O+RXVTTeCOhIGWuM6QqIz5V1+/7qAK0iIEaFJpBDnNQ2yNRe0s7upov0KsL0aL5kMZrxn+7QwVQmgmx7dFbI2PYnWFyFIqY2dDplYEuwJ+T81HxglgaaKoQGxhse6BBepfM3GVYYBf+mq8O4TgARjoXsUYMRS/Ru8vQ2E73G210lC3uOqBf1zrR4xBpqCdNEQvY6y+H9BqWYcKcNtFaXSERMTzeWWaV73xQ7wPYRixHDRPkjPVaBD/p7iGeEVyOaQKBgQDaBziILzLF3aoEjhfb9y460degEv1Bpy49I1rdTYl6w1/a+ItJYRRA9ZzepRv8QdjxdzqoAZE1E3IEtK35xEeMV5yzF6wsJ/c9lNh3FumAcFOMsCEcNXsuVoplltHdLue8r5GkuoA7loI207RqGR4/+s/nWd2NSFw49iRpKVrauwKBgQC+UYYq8Zv7oZVPjb/LOPOaM+3Q0GsbQC3Kmzp7sjiqcBbpZXp4EY+L9Jd/O2I3Shkips3IN2g5OEj0Q91G+K4olV+FCjvEKIPGN1x6VaCFrsi82qsrwWoTd9+rCaxrASOiXbPtzJc87hSpCG/05xe8X0X9J8RVFqWtjHg/o/abVQKBgDEBzIA387asE4pAkjZcQiTwhAI0In7+YBNX/hWeVxekEMi8czqEOrQ7QQ5+mGLEPkpQXXvkFkqS218Zab2pk9eE3fEXkhi+xwEtktZ57PR0yyLleBvKHa0VwLgDBZss7uPnptobHbXHJ+/A+F2c1cLV0qOS/IzERg57rUWCCSz/AoGACxQl0kQkR16dmXbv7j2PeK+DLX+kbH6s67ljiyXRxKInw0hj+69SAtynIQHs8rj+g5TgL8KB76rGHGoC7Im3YadoWw9AcWfGW/iHCpwHbyDAkLXN9wsYSK/Wtlcm0UfMsjvwKGybdTGKxFg4ZDI7oHyPT3BMLoPV+ydNLK83wM0CgYEAkxR3Mn/9a77O9bbxP1Du6r/brSKZ4G51ZrdVQo05CrWGwaiBW3b+ZtConhE6ASOTNdzHL1WvSF07QuBg5qRCQIks/XQYoxTwxwABPp/vKJ7Gh23siRzqYBEHm+L1kqNboOeJbWOzHhRAPwW54Wq3SJHsTDgyXpns4CUiVGIPxzg=", // 应用私钥 必填
			BizToken:        "test_biz_token",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // 业务令牌，访问灯火平台的token，必填
			PrincipalTag:    "test_principal_tag",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // 商家标签，必填
			BizNo:           "test_biz_no",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 转化流水号，由商家自主定义作为转化数据唯一标识 , 必填
			ConversionType:  "425",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // 转化事件类型，必填
			ConversionTime:  1730270543,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // 转化时间，秒级时间戳
			CallbackExtInfo: "xx",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // callback , 监测获取，必填
		},
	}

	// step2. 获取回传工厂的实例
	convH, err := conv.NewChannelHandler("alipay")
	if err != nil {
		panic(err)
	}
	// step3. 调用回传
	convRes, err := convH.DoConv(context.Background(), convReq)
	if err != nil {
		panic(err)
	}

	fmt.Println(convRes)
}
